(() => {
  'use strict';
  const STORAGE_KEY = 'softtrack-state-v1', SCHEMA = 1;
  const STATUSES = ['Backlog','Planejado','Em desenvolvimento','Em revisão','Em testes','Bloqueado','Concluído'];
  const TYPES = ['Funcionalidade','Tarefa','Teste','Bug','Correção','Refatoração','Documentação','Melhoria','Dívida técnica'];
  const PRIORITIES = ['Crítica','Alta','Média','Baixa'];
  const TEMPLATES = { 'Funcionalidade': [['Implementar','Tarefa'],['Tratar erros','Tarefa'],['Criar testes','Teste'],['Revisar funcionalidade','Tarefa'],['Atualizar documentação','Documentação']], Bug: [['Investigar causa','Tarefa'],['Corrigir','Correção'],['Criar teste de regressão','Teste'],['Validar correção','Teste']], Refatoração: [['Identificar comportamento atual','Tarefa'],['Refatorar','Refatoração'],['Executar testes','Teste'],['Verificar regressões','Teste']] };
  const DONE = ['Implementação concluída','Testes criados','Testes verificados','Bugs conhecidos resolvidos','Revisão realizada','Documentação verificada'];
  const $ = s => document.querySelector(s); let state, view = 'board', filter = 'all', query = '', importData = null;
  const uid = () => crypto.randomUUID ? crypto.randomUUID() : `id-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const now = () => new Date().toISOString();
  const item = (title,type='Tarefa', extra={}) => ({id:uid(),title,description:'',currentBehavior:'',expectedResult:'',type,priority:'Média',status:'Backlog',createdAt:now(),updatedAt:now(),tags:[],checklist:[],notes:'',relatedId:'',blocked:false,blockReason:'',...extra});
  function demo(){ const auth=item('Autenticação de usuários','Funcionalidade',{priority:'Alta',status:'Em desenvolvimento',checklist:DONE.map((text,i)=>({text,done:i<2}))}); const dash=item('Dashboard inicial','Funcionalidade',{status:'Planejado',priority:'Média',checklist:DONE.map(text=>({text,done:false}))}); const signup=item('Cadastro de usuário','Funcionalidade',{status:'Concluído',checklist:DONE.map(text=>({text,done:true}))}); const children=[item('Implementar login','Tarefa',{relatedId:auth.id,status:'Em desenvolvimento',priority:'Alta'}),item('Testar login inválido','Teste',{relatedId:auth.id,status:'Em testes'}),item('Corrigir sessão expirada','Bug',{relatedId:auth.id,status:'Bloqueado',priority:'Crítica',blocked:true,blockReason:'Aguardando definição de segurança'}),item('Documentar autenticação','Documentação',{relatedId:auth.id,status:'Backlog'}),item('Criar cards do dashboard','Tarefa',{relatedId:dash.id,status:'Planejado'}),item('Testar cadastro','Teste',{relatedId:signup.id,status:'Concluído'})]; return {schemaVersion:SCHEMA,activeProjectId:'demo',projects:[{id:'demo',name:'Meu App',items:[auth,dash,signup,...children]}]}; }
  function normalize(data){data.projects.forEach(p=>p.items.forEach(i=>{i.checklist=(i.checklist||[]).map(c=>({id:c.id||uid(),title:c.title||c.text||'',description:c.description||'',completed:!!(c.completed||c.done)}));}));return data}
  function load(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return normalize(demo());const data=JSON.parse(raw);return valid(data)?normalize(data):normalize(demo())}catch{return normalize(demo())}}
  function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
  function valid(d){return d&&d.schemaVersion===SCHEMA&&Array.isArray(d.projects)&&d.projects.every(p=>typeof p.id==='string'&&typeof p.name==='string'&&Array.isArray(p.items))}
  function project(){return state.projects.find(p=>p.id===state.activeProjectId)||state.projects[0]}
  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
  function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function detailFields(){const label=$('#description').closest('label');label.insertAdjacentHTML('afterend','<label>Comportamento atual <button type="button" class="help" data-help="Descreva o que acontece hoje, incluindo mensagens, telas ou valores incorretos.">ⓘ</button><textarea id="currentBehavior" rows="2" placeholder="Ex.: aparece apenas o nome do atendente."></textarea></label><label>Resultado esperado <button type="button" class="help" data-help="Descreva claramente o resultado que deve existir quando o item estiver pronto.">ⓘ</button><textarea id="expectedResult" rows="2" placeholder="Ex.: mostrar nome e número, sem valores inválidos."></textarea></label>')}
  function init(){state=load();detailFields();if(!state.activeProjectId&&state.projects[0])state.activeProjectId=state.projects[0].id; bind();$('#copyItemPromptBtn').onclick=()=>{const i=project().items.find(x=>x.id===$('#itemId').value);if(i)openPrompt([i])};$('#copyPromptBtn').onclick=copyPrompt;document.addEventListener('click',e=>{const h=e.target.closest('.help');if(h)toast(h.dataset.help);const m=e.target.closest('#copyMissingPromptBtn');if(m){const ids=[...document.querySelectorAll('.prompt-select:checked')].map(x=>x.value);openPrompt(project().items.filter(i=>ids.includes(i.id)))}const o=e.target.closest('[data-open]');if(o)openItem(o.dataset.open)});render()}
  function bind(){ $('#projectSelect').onchange=e=>{state.activeProjectId=e.target.value;save();render()}; $('#newProjectBtn').onclick=()=>$('#projectDialog').showModal(); $('#projectForm').onsubmit=e=>{e.preventDefault();const name=$('#newProjectName').value.trim();if(!name)return;const p={id:uid(),name,items:[]};state.projects.push(p);state.activeProjectId=p.id;save();e.target.reset();$('#projectDialog').close();render();toast('Projeto criado')}; $('#renameProjectBtn').onclick=()=>{const name=prompt('Novo nome do projeto:',project().name);if(name?.trim()){project().name=name.trim();save();render()}}; $('#deleteProjectBtn').onclick=()=>{if(confirm(`Excluir "${project().name}" e todos os seus itens?`)){state.projects=state.projects.filter(p=>p.id!==project().id);if(!state.projects.length){const p={id:uid(),name:'Novo projeto',items:[]};state.projects=[p]}state.activeProjectId=state.projects[0].id;save();render();toast('Projeto excluído')}}; $('#newItemBtn').onclick=()=>openItem(); $('#views').onclick=e=>{if(e.target.dataset.view){view=e.target.dataset.view;render()}}; $('#filters').onclick=e=>{if(e.target.dataset.filter){filter=e.target.dataset.filter;render()}}; $('#searchInput').oninput=e=>{query=e.target.value.toLowerCase();renderContent()}; document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close()); $('#blocked').onchange=()=>$('#blockReasonWrap').hidden=!$('#blocked').checked; $('#addChecklistBtn').onclick=()=>addCheck(); $('#itemForm').onsubmit=saveItem; $('#deleteItemBtn').onclick=deleteItem; $('#exportProjectBtn').onclick=()=>download({schemaVersion:SCHEMA,projects:[project()]},`${safe(project().name)}.json`); $('#exportAllBtn').onclick=()=>download(state,'softtrack-todos-projetos.json'); $('#importInput').onchange=readImport; $('#importForm').onsubmit=applyImport; $('#clearBtn').onclick=()=>{if(confirm('Limpar todos os dados locais? Esta ação não pode ser desfeita.')){localStorage.removeItem(STORAGE_KEY);state=demo();save();render();toast('Dados locais reiniciados')}}; }
  function render(){const p=project();$('#projectSelect').innerHTML=state.projects.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${esc(x.name)}</option>`).join('');$('#projectName').textContent=p.name;const s=stats(p.items);$('#progressPercent').textContent=`${s.progress}%`;$('#progressBar').style.width=`${s.progress}%`;$('#missingCount').textContent=missing(p.items).length||'';document.querySelectorAll('#views button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('#filters button').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));renderContent()}
  function stats(items){const done=items.filter(i=>i.status==='Concluído').length,total=items.length, ongoing=items.filter(i=>i.status==='Em desenvolvimento').length;return {total,done,ongoing,bugs:items.filter(i=>i.type==='Bug'&&i.status!=='Concluído').length,tests:items.filter(i=>i.type==='Teste'&&i.status!=='Concluído').length,blocked:items.filter(i=>i.blocked||i.status==='Bloqueado').length,review:items.filter(i=>i.status==='Em revisão').length,checklist:items.reduce((n,i)=>n+(i.checklist||[]).filter(c=>!c.completed).length,0),progress:total?Math.round(done/total*100):0}}
  function promptFor(items){const active=items.filter(i=>i.status!=='Concluído'),single=active.length===1;const blocks=[];const add=(title,value)=>{if(value?.trim())blocks.push(`${title}\n\n${value.trim()}`)};if(single){const i=active[0],checks=(i.checklist||[]).filter(c=>!c.completed).map(c=>`- ${c.title}${c.description?`: ${c.description}`:''}`).join('\n'),related=project().items.filter(x=>x.relatedId===i.id&&x.status!=='Concluído').map(x=>`- ${x.type}: ${x.title}`).join('\n');add('OBJETIVO',`Resolver ${i.type.toLowerCase()} “${i.title}”.${i.description?`\n\n${i.description}`:''}`);add('COMPORTAMENTO ATUAL',i.currentBehavior);add('COMPORTAMENTO ESPERADO',i.expectedResult);add('PASSOS PARA REPRODUZIR',i.notes);add('PENDÊNCIAS',[checks,related].filter(Boolean).join('\n'));if(i.blocked)add('RESTRIÇÕES',`O trabalho está bloqueado: ${i.blockReason||'motivo ainda não informado.'}`);add('VALIDAÇÃO',i.expectedResult?`Confirme que: ${i.expectedResult}`:'Verifique o resultado visualmente e confirme que a pendência foi resolvida.');return blocks.join('\n\n')}const entries=active.map((i,n)=>`${n+1}. ${i.type.toUpperCase()} — ${i.title}\nPrioridade: ${i.priority}${i.currentBehavior?`\nComportamento atual: ${i.currentBehavior}`:''}${i.expectedResult?`\nResultado esperado: ${i.expectedResult}`:''}${i.blocked?`\nBloqueio: ${i.blockReason||'motivo não informado'}`:''}`).join('\n\n');add('OBJETIVO',`Resolver as pendências selecionadas do projeto “${project().name}”.`);add('PENDÊNCIAS',entries);add('VALIDAÇÃO','Ao finalizar, revise os itens e informe quais foram concluídos e quais permanecem pendentes.');return blocks.join('\n\n')}
  function openPrompt(items){const pending=items.filter(i=>i.status!=='Concluído');if(!pending.length){toast('Não existem pendências para copiar');return}$('#promptPreview').value=promptFor(pending);$('#promptDialog').showModal()}
  function copyPrompt(){const text=$('#promptPreview').value;const done=()=>{toast('Prompt copiado!');$('#promptDialog').close()};if(navigator.clipboard?.writeText)navigator.clipboard.writeText(text).then(done).catch(()=>{ $('#promptPreview').select();document.execCommand('copy');done() });else{$('#promptPreview').select();document.execCommand('copy');done()}}
  function passes(i){return (!query||`${i.title} ${i.description} ${i.tags.join(' ')}`.toLowerCase().includes(query))&&(filter==='all'||(filter==='blocked'&&(i.blocked||i.status==='Bloqueado'))||(filter==='high'&&(i.priority==='Alta'||i.priority==='Crítica'))||i.type===filter)}
  function card(i){const related=project().items.filter(x=>x.relatedId===i.id), complete=related.filter(x=>x.status==='Concluído').length;return `<article class="card" draggable="true" data-id="${i.id}"><div class="card-top"><span class="type-pill type-${i.type.replace(' ','-')}">${esc(i.type)}</span>${i.blocked?'<span class="blocked">●</span>':''}</div><h3>${esc(i.title)}</h3><div class="card-bottom"><span class="priority-${i.priority}">● ${i.priority}</span><span>${related.length?`${complete}/${related.length} relacionados`:i.checklist.length?`${i.checklist.filter(c=>c.completed).length}/${i.checklist.length} checklist`:''}</span></div></article>`}
  function renderContent(){const p=project(), el=$('#content'),items=p.items.filter(passes);if(view==='board'){el.innerHTML=`<div class="board">${STATUSES.map(st=>{const its=items.filter(i=>i.status===st);return `<section class="column" data-status="${st}"><header class="column-head">${st}<span>${its.length}</span></header><div class="card-list">${its.map(card).join('')||'<p class="empty">Nenhum item</p>'}</div></section>`}).join('')}</div>`;bindCards();return}const s=stats(p.items);if(view==='missing'){const groups=missing(p.items),pending=p.items.filter(i=>i.status!=='Concluído');el.innerHTML=`<div class="stat-grid">${statCards(s)}</div><section class="missing-group"><h3>Pendências para IA</h3><button id="copyMissingPromptBtn">Copiar pendências selecionadas para IA</button><ul>${pending.map(i=>`<li><label><input type="checkbox" class="prompt-select" value="${i.id}" ${(i.priority==='Crítica'||i.priority==='Alta')?'checked':''}> ${esc(i.title)} — ${i.priority}</label></li>`).join('')}</ul></section><div class="missing-grid">${groups.map(g=>`<section class="missing-group"><h3>${g.icon} ${g.title} <span class="badge">${g.items.length}</span></h3><ul>${g.items.map(i=>`<li data-open="${i.id}">${esc(i.title)}</li>`).join('')}</ul></section>`).join('')||'<p class="empty">Nada pendente. Ótimo trabalho!</p>'}</div>`;return}const type=view==='bugs'?'Bug':'Teste';if(view===type.toLowerCase()+'s'||view==='bugs'||view==='tests'){const arr=p.items.filter(i=>i.type===type);el.innerHTML=`<div class="stat-grid">${statCards(s)}</div><div class="missing-grid"><section class="missing-group"><h3>${type}s</h3>${arr.length?`<ul>${arr.map(i=>`<li>${esc(i.title)} <small>— ${i.status}</small></li>`).join('')}</ul>`:'<p class="empty">Nenhum item.</p>'}</section></div>`;return}const pending=p.items.filter(i=>i.status!=='Concluído').sort((a,b)=>(b.blocked-a.blocked)||PRIORITIES.indexOf(a.priority)-PRIORITIES.indexOf(b.priority));el.innerHTML=`<div class="stat-grid">${statCards(s)}</div><section class="missing-group"><h3>Principais pendências</h3><ol class="summary-list">${pending.slice(0,8).map(i=>`<li>${i.blocked?'⛔ ':''}${esc(i.title)} <small>— ${i.status} · ${i.priority}</small></li>`).join('')||'<li>Projeto concluído.</li>'}</ol></section>`}
  function statCards(s){return [[s.total,'Total de itens'],[s.done,'Concluídos'],[s.ongoing,'Em andamento'],[s.bugs,'Bugs abertos'],[s.tests,'Testes pendentes'],[s.blocked,'Bloqueados'],[s.review,'Em revisão'],[s.checklist,'Checklist pendente']].map(x=>`<div class="stat"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}
  function missing(items){const f=(fn,title,icon='•')=>{const a=items.filter(fn);return a.length?{items:a,title,icon}:null};const funcs=items.filter(i=>i.type==='Funcionalidade');return [f(i=>i.type==='Funcionalidade'&&i.status!=='Concluído','Funcionalidades não concluídas','◈'),f(i=>i.type==='Bug'&&i.status!=='Concluído','Bugs abertos','🐞'),f(i=>i.type==='Bug'&&i.priority==='Crítica'&&i.status!=='Concluído','Bugs críticos','⚠'),f(i=>i.type==='Teste'&&i.status!=='Concluído','Testes pendentes','🧪'),f(i=>i.blocked||i.status==='Bloqueado','Trabalho bloqueado','⛔'),f(i=>i.status==='Em desenvolvimento','Em desenvolvimento','◐'),f(i=>i.status==='Em revisão','Aguardando revisão','⌕'),f(i=>i.type==='Documentação'&&i.status!=='Concluído','Documentação pendente','▤'),f(i=>(i.priority==='Alta'||i.priority==='Crítica')&&i.status!=='Concluído','Alta prioridade','▲'),f(i=>funcs.includes(i)&&!items.some(x=>x.relatedId===i.id&&x.type==='Teste'),'Funcionalidades sem testes','⚠')].filter(Boolean)}
  function bindCards(){
    document.querySelectorAll('.card').forEach(c=>{
      c.ondragstart=e=>{e.dataTransfer.setData('text/plain',c.dataset.id);c.classList.add('dragging')};
      c.ondragend=()=>c.classList.remove('dragging'); c.onclick=()=>openItem(c.dataset.id);
    });
    document.querySelectorAll('.column').forEach(c=>{
      c.ondragover=e=>{e.preventDefault();c.classList.add('drag-over')};
      c.ondragleave=()=>c.classList.remove('drag-over');
      c.ondrop=e=>{e.preventDefault();c.classList.remove('drag-over');const i=project().items.find(x=>x.id===e.dataTransfer.getData('text/plain'));if(i){i.status=c.dataset.status;i.blocked=i.status==='Bloqueado'||i.blocked;i.updatedAt=now();save();render();toast('Item movido')}};
    });
  }
  function options(arr,value){return arr.map(x=>`<option ${x===value?'selected':''}>${x}</option>`).join('')}
  function openItem(id){const i=project().items.find(x=>x.id===id);$('#itemForm').reset();$('#itemId').value=i?.id||'';$('#modalTitle').textContent=i?'Editar item':'Novo item';$('#type').innerHTML=options(TYPES,i?.type||'Tarefa');$('#priority').innerHTML=options(PRIORITIES,i?.priority||'Média');$('#status').innerHTML=options(STATUSES,i?.status||'Backlog');const rel=project().items.filter(x=>x.id!==i?.id);$('#relatedId').innerHTML='<option value="">Nenhum</option>'+rel.map(x=>`<option value="${x.id}" ${x.id===i?.relatedId?'selected':''}>${esc(x.title)}</option>`).join('');['title','description','currentBehavior','expectedResult','tags','notes','blockReason'].forEach(k=>$('#'+k).value=k==='tags'?(i?.tags||[]).join(', '):(i?.[k]||''));$('#blocked').checked=!!i?.blocked;$('#blockReasonWrap').hidden=!i?.blocked;$('#checklistFields').innerHTML='';(i?.checklist||[]).forEach(addCheck);$('#deleteItemBtn').hidden=!i;const children=i?project().items.filter(x=>x.relatedId===i.id):[];$('#relatedSection').innerHTML=children.length?`<strong>Itens relacionados (${children.filter(x=>x.status==='Concluído').length} concluídos, ${children.filter(x=>x.blocked||x.status==='Bloqueado').length} bloqueados)</strong><ul>${children.map(x=>`<li>${esc(x.title)} — ${x.status}</li>`).join('')}</ul>`:'';$('#itemDialog').showModal()}
  function addCheck(c={title:'',description:'',completed:false}){const row=document.createElement('div');row.className='check-row';row.innerHTML=`<input type="checkbox" ${c.completed?'checked':''}><div class="check-fields"><input class="check-title" type="text" value="${esc(c.title||c.text)}" placeholder="O que precisa ser feito?"><input class="check-desc" type="text" value="${esc(c.description||'')}" placeholder="Explique o resultado esperado"></div><button type="button" class="remove-check">×</button>`;row.querySelector('.remove-check').onclick=()=>row.remove();$('#checklistFields').append(row)}
  function saveItem(e){e.preventDefault();const p=project(), existing=p.items.find(i=>i.id===$('#itemId').value), type=$('#type').value;const data={title:$('#title').value.trim(),description:$('#description').value.trim(),currentBehavior:$('#currentBehavior').value.trim(),expectedResult:$('#expectedResult').value.trim(),type,priority:$('#priority').value,status:$('#status').value,tags:$('#tags').value.split(',').map(x=>x.trim()).filter(Boolean),relatedId:$('#relatedId').value,blocked:$('#blocked').checked,blockReason:$('#blockReason').value.trim(),notes:$('#notes').value.trim(),checklist:[...document.querySelectorAll('#checklistFields .check-row')].map(r=>({id:uid(),completed:r.querySelector('[type=checkbox]').checked,title:r.querySelector('.check-title').value.trim(),description:r.querySelector('.check-desc').value.trim()})).filter(c=>c.title),updatedAt:now()};if(existing)Object.assign(existing,data);else{const newI=item(data.title,type,data);p.items.push(newI);if(TEMPLATES[type]&&confirm(`Gerar ${TEMPLATES[type].length} tarefas relacionadas automaticamente?`)){TEMPLATES[type].forEach(([name,t])=>p.items.push(item(`${name}: ${data.title}`,t,{relatedId:newI.id,priority:data.priority})));}if(type==='Funcionalidade'&&!data.checklist.length)newI.checklist=DONE.map(text=>({id:uid(),title:text,description:'Critério necessário para considerar a funcionalidade pronta.',completed:false}));}save();$('#itemDialog').close();render();toast(existing?'Item atualizado':'Item criado')}
  function deleteItem(){const id=$('#itemId').value;if(confirm('Excluir este item? Os itens relacionados serão mantidos sem vínculo.')){project().items.forEach(i=>{if(i.relatedId===id)i.relatedId=''});project().items=project().items.filter(i=>i.id!==id);save();$('#itemDialog').close();render();toast('Item excluído')}}
  function download(data,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href);toast('Exportação preparada')};function safe(s){return s.replace(/[^a-z0-9]/gi,'-').toLowerCase()}
  function readImport(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const d=JSON.parse(reader.result);if(!valid(d))throw Error();importData=d;$('#importInfo').textContent=`Arquivo válido: ${d.projects.length} projeto(s). Escolha como combinar os dados.`;$('#importDialog').showModal()}catch{toast('JSON inválido ou incompatível')}};reader.readAsText(file);e.target.value=''}function applyImport(e){e.preventDefault();if(!importData)return;const mode=$('#importMode').value;if(mode==='replace')state=importData;else{const existing=new Set(state.projects.map(p=>p.id));const incoming=importData.projects.map(p=>existing.has(p.id)?{...p,id:uid(),name:`${p.name} (importado)`}:p);state.projects.push(...incoming)}state.activeProjectId=state.projects[0]?.id||'';save();$('#importDialog').close();render();toast('Dados importados com sucesso')}
  init();
})();
