(() => {
  'use strict';
  const STORAGE_KEY = 'softtrack-state-v1', SETTINGS_KEY = 'softtrack-settings-v1', BACKUP_DB = 'softtrack-backup-handles', SCHEMA = 1;
  const STATUSES = ['Backlog','Planejado','Em desenvolvimento','Em revisão','Em testes','Bloqueado','Concluído'];
  const TYPES = ['Funcionalidade','Tarefa','Teste','Bug','Correção','Refatoração','Documentação','Melhoria','Dívida técnica'];
  const PRIORITIES = ['Crítica','Alta','Média','Baixa'];
  const TEMPLATES = { 'Funcionalidade': [['Implementar','Tarefa'],['Tratar erros','Tarefa'],['Criar testes','Teste'],['Revisar funcionalidade','Tarefa'],['Atualizar documentação','Documentação']], Bug: [['Investigar causa','Tarefa'],['Corrigir','Correção'],['Criar teste de regressão','Teste'],['Validar correção','Teste']], Refatoração: [['Identificar comportamento atual','Tarefa'],['Refatorar','Refatoração'],['Executar testes','Teste'],['Verificar regressões','Teste']] };
  const DONE = ['Implementação concluída','Testes criados','Testes verificados','Bugs conhecidos resolvidos','Revisão realizada','Documentação verificada'];
  const STATUS_HELP = {Backlog:'Local para itens que foram identificados, mas ainda não foram escolhidos para começar. Use para guardar funcionalidades, bugs, melhorias e tarefas que serão avaliadas depois.',Planejado:'Item que já foi escolhido para ser realizado, mas cujo desenvolvimento ainda não começou.','Em desenvolvimento':'Item que está sendo implementado, alterado ou corrigido neste momento.','Em revisão':'A implementação principal já foi realizada, mas ainda precisa ser conferida antes de seguir para testes ou conclusão.','Em testes':'Item que está sendo validado para confirmar se funciona corretamente e se não causou outros problemas.',Bloqueado:'Item que não pode continuar por causa de outra tarefa, problema, dependência ou informação ausente. Informe sempre o motivo do bloqueio.',Concluído:'Item cujo trabalho necessário foi finalizado. Antes de concluir, verifique checklist, testes e pendências relacionadas quando aplicável.'};
  const $ = s => document.querySelector(s); let state, settings, view = 'board', filter = 'all', query = '', importData = null, backupTimer = null, backupInProgress = false;
  const backupHandles = {primary:null,secondary:null};
  const uid = () => crypto.randomUUID ? crypto.randomUUID() : `id-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const now = () => new Date().toISOString();
  const item = (title,type='Tarefa', extra={}) => ({id:uid(),title,description:'',type,priority:'Média',status:'Backlog',createdAt:now(),updatedAt:now(),tags:[],checklist:[],notes:'',relatedId:'',blocked:false,blockReason:'',...extra});
  function demo(){ const auth=item('Autenticação de usuários','Funcionalidade',{priority:'Alta',status:'Em desenvolvimento',checklist:DONE.map((text,i)=>({text,done:i<2}))}); const dash=item('Dashboard inicial','Funcionalidade',{status:'Planejado',priority:'Média',checklist:DONE.map(text=>({text,done:false}))}); const signup=item('Cadastro de usuário','Funcionalidade',{status:'Concluído',checklist:DONE.map(text=>({text,done:true}))}); const children=[item('Implementar login','Tarefa',{relatedId:auth.id,status:'Em desenvolvimento',priority:'Alta'}),item('Testar login inválido','Teste',{relatedId:auth.id,status:'Em testes'}),item('Corrigir sessão expirada','Bug',{relatedId:auth.id,status:'Bloqueado',priority:'Crítica',blocked:true,blockReason:'Aguardando definição de segurança'}),item('Documentar autenticação','Documentação',{relatedId:auth.id,status:'Backlog'}),item('Criar cards do dashboard','Tarefa',{relatedId:dash.id,status:'Planejado'}),item('Testar cadastro','Teste',{relatedId:signup.id,status:'Concluído'})]; return {schemaVersion:SCHEMA,activeProjectId:'demo',projects:[{id:'demo',name:'Meu App',items:[auth,dash,signup,...children]}]}; }
  function normalize(data){data.projects.forEach(p=>p.items.forEach(i=>{i.checklist=(i.checklist||[]).map(c=>({id:c.id||uid(),title:c.title||c.text||'',description:c.description||'',completed:!!(c.completed||c.done)}));}));return data}
  function load(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return normalize(demo());const data=JSON.parse(raw);return valid(data)?normalize(data):normalize(demo())}catch{return normalize(demo())}}
  function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
  function valid(d){return d&&d.schemaVersion===SCHEMA&&Array.isArray(d.projects)&&d.projects.every(p=>typeof p.id==='string'&&typeof p.name==='string'&&Array.isArray(p.items))}
  function project(){return state.projects.find(p=>p.id===state.activeProjectId)||state.projects[0]}
  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
  function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function defaultSettings(){return {autoBackup:false,interval:30,lastAttempt:'',nextBackup:'',destinations:{primary:{name:'',status:'not-configured',lastAt:''},secondary:{name:'',status:'not-configured',lastAt:''}}}}
  function normalizeSettings(saved={}){const defaults=defaultSettings(),source=saved&&typeof saved==='object'?saved:{},destinations=source.destinations&&typeof source.destinations==='object'?source.destinations:{};return {...defaults,...source,destinations:{primary:{...defaults.destinations.primary,...destinations.primary},secondary:{...defaults.destinations.secondary,...destinations.secondary}}}}
  function loadSettings(){try{return normalizeSettings(JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}'))}catch{return defaultSettings()}}
  function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))}
  function supportsBackup(){return 'showDirectoryPicker' in window&&'indexedDB' in window}
  function openBackupDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(BACKUP_DB,1);request.onupgradeneeded=()=>request.result.createObjectStore('handles');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
  async function handleStore(action,key,value){const db=await openBackupDb();return new Promise((resolve,reject)=>{const tx=db.transaction('handles','readwrite'),store=tx.objectStore('handles'),request=action==='get'?store.get(key):action==='put'?store.put(value,key):store.delete(key);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close();tx.onerror=()=>reject(tx.error)})}
  async function hasWritePermission(handle,request=false){if(!handle)return false;try{let permission=await handle.queryPermission({mode:'readwrite'});if(permission!=='granted'&&request)permission=await handle.requestPermission({mode:'readwrite'});return permission==='granted'}catch{return false}}
  async function restoreBackupHandles(){if(!supportsBackup()||!('indexedDB' in window))return;for(const key of ['primary','secondary']){try{const handle=await handleStore('get',key);if(handle){backupHandles[key]=handle;settings.destinations[key].name=handle.name||settings.destinations[key].name;settings.destinations[key].status=await hasWritePermission(handle)?'ready':'needs-permission'}}catch{settings.destinations[key].status=settings.destinations[key].name?'needs-selection':'not-configured'}}saveSettings();refreshBackupTimer();if(view==='settings')renderContent();renderBackupIndicator()}
  function init(){state=load();settings=loadSettings();bindHelpTooltips();if(!state.activeProjectId&&state.projects[0])state.activeProjectId=state.projects[0].id; bind();$('#copyItemPromptBtn').onclick=()=>{const i=project().items.find(x=>x.id===$('#itemId').value);if(i)openPrompt([i])};$('#copyPromptBtn').onclick=copyPrompt;document.addEventListener('click',e=>{const m=e.target.closest('#copyMissingPromptBtn');if(m){const ids=[...document.querySelectorAll('.prompt-select:checked')].map(x=>x.value);openPrompt(project().items.filter(i=>ids.includes(i.id)))}const o=e.target.closest('[data-open]');if(o)openItem(o.dataset.open)});render();restoreBackupHandles();refreshBackupTimer()}
  function bindHelpTooltips(){const tip=$('#helpTooltip');let active=null,pinned=false;const position=()=>{if(!active||tip.hidden)return;const r=active.getBoundingClientRect(),gap=7;tip.style.left='0px';tip.style.top='0px';const w=tip.offsetWidth,h=tip.offsetHeight;let left=Math.min(Math.max(12,r.left),window.innerWidth-w-12),top=r.bottom+gap;if(top+h>window.innerHeight-12)top=Math.max(12,r.top-h-gap);tip.style.left=`${Math.round(left)}px`;tip.style.top=`${Math.round(top)}px`};const show=(button,keepOpen=false)=>{const host=button.closest('dialog')||document.body;if(tip.parentElement!==host)host.append(tip);active=button;pinned=keepOpen;tip.textContent=button.dataset.help||'';tip.hidden=false;if(!button.getAttribute('aria-label'))button.setAttribute('aria-label','Ajuda');button.setAttribute('aria-describedby','helpTooltip');button.setAttribute('aria-expanded','true');requestAnimationFrame(position)};const hide=()=>{if(!active)return;active.removeAttribute('aria-describedby');active.setAttribute('aria-expanded','false');active=null;pinned=false;tip.hidden=true};document.addEventListener('pointerover',e=>{const button=e.target.closest('.help');if(button)show(button)});document.addEventListener('pointerout',e=>{const button=e.target.closest('.help');if(button&&!button.contains(e.relatedTarget)&&!pinned)hide()});document.addEventListener('focusin',e=>{const button=e.target.closest('.help');if(button)show(button)});document.addEventListener('focusout',e=>{const button=e.target.closest('.help');if(button&&!pinned)hide()});document.addEventListener('click',e=>{const button=e.target.closest('.help');if(button){e.preventDefault();e.stopPropagation();active===button&&!tip.hidden&&pinned?hide():show(button,true)}else if(active&&pinned)hide()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&active)hide()});window.addEventListener('resize',position);document.addEventListener('scroll',position,true)}
  function formatBackupDate(value){return value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'Ainda não realizada'}
  function refreshBackupTimer(){if(backupTimer){clearTimeout(backupTimer);backupTimer=null}settings.nextBackup='';if(settings.autoBackup&&(supportsBackup()?(backupHandles.primary||backupHandles.secondary):true)){const delay=settings.interval*60*1000;settings.nextBackup=new Date(Date.now()+delay).toISOString();backupTimer=setTimeout(async()=>{if(supportsBackup())await runBackup();else downloadBackupFallback(true);refreshBackupTimer();if(view==='settings')renderContent()},delay)}saveSettings();renderBackupIndicator()}
  async function writeBackup(key,payload){const handle=backupHandles[key];if(!handle)return {status:'not-configured',message:'Pasta não configurada'};if(!await hasWritePermission(handle)){return {status:'needs-permission',message:'Precisa de autorização novamente'}}try{const file=await handle.getFileHandle('softengine-backup.json',{create:true}),writer=await file.createWritable();await writer.write(payload);await writer.close();return {status:'saved',message:'Salvo'}}catch{return {status:'failed',message:'Não foi possível salvar'}}}
  function exportData(projects=state.projects){return {schemaVersion:SCHEMA,activeProjectId:state.activeProjectId,projects,settings}}
  async function runBackup(manual=false){if(backupInProgress)return;const configured=['primary','secondary'].filter(key=>backupHandles[key]);if(!configured.length){if(manual)toast('Configure pelo menos uma pasta para usar o backup automático.');return}backupInProgress=true;settings.lastAttempt=new Date().toISOString();const payload=JSON.stringify(exportData(),null,2);for(const key of ['primary','secondary']){if(!backupHandles[key]||settings.destinations[key].status==='needs-permission')continue;const result=await writeBackup(key,payload);Object.assign(settings.destinations[key],{status:result.status,lastAt:settings.lastAttempt})}backupInProgress=false;saveSettings();renderBackupIndicator();if(view==='settings')renderContent();if(manual)toast('Tentativa de backup finalizada. Confira o status dos destinos.')}
  async function chooseBackupDirectory(key){if(!supportsBackup()){toast('Este navegador não permite selecionar pastas para backup.');return}try{const handle=await window.showDirectoryPicker({mode:'readwrite'});backupHandles[key]=handle;await handleStore('put',key,handle);Object.assign(settings.destinations[key],{name:handle.name||'',status:await hasWritePermission(handle)?'ready':'needs-permission',lastAt:''});saveSettings();refreshBackupTimer();renderContent()}catch(error){if(error?.name!=='AbortError')toast('Não foi possível selecionar esta pasta.')}}
  async function removeBackupDirectory(key){backupHandles[key]=null;try{await handleStore('delete',key)}catch{}settings.destinations[key]={name:'',status:'not-configured',lastAt:''};saveSettings();refreshBackupTimer();renderContent()}
  async function authorizeBackupDirectory(key){const handle=backupHandles[key];if(!handle){toast('Selecione a pasta novamente para autorizar o backup.');return}const authorized=await hasWritePermission(handle,true);settings.destinations[key].status=authorized?'ready':'needs-permission';saveSettings();refreshBackupTimer();renderContent();if(!authorized)toast('A autorização não foi concedida.')}
  function renderBackupIndicator(){const indicator=$('#backupIndicator');if(!indicator)return;const browserDownload=settings?.autoBackup&&!supportsBackup(),configured=settings?.autoBackup&&supportsBackup()&&(backupHandles.primary||backupHandles.secondary),needsPermission=['primary','secondary'].some(key=>settings?.destinations[key].status==='needs-permission');indicator.textContent=browserDownload?'Backup ↓':configured&&!needsPermission?'Backup ✓':configured?'Backup ⚠':'Backup';indicator.classList.toggle('has-warning',!!settings?.autoBackup&&!browserDownload&&(!configured||needsPermission))}
  function bind(){ $('#projectSelect').onchange=e=>{state.activeProjectId=e.target.value;save();render()}; $('#newProjectBtn').onclick=()=>$('#projectDialog').showModal(); $('#projectForm').onsubmit=e=>{e.preventDefault();const name=$('#newProjectName').value.trim();if(!name)return;const p={id:uid(),name,items:[]};state.projects.push(p);state.activeProjectId=p.id;save();e.target.reset();$('#projectDialog').close();render();toast('Projeto criado')}; $('#renameProjectBtn').onclick=()=>{const name=prompt('Novo nome do projeto:',project().name);if(name?.trim()){project().name=name.trim();save();render()}}; $('#deleteProjectBtn').onclick=()=>{if(confirm(`Excluir "${project().name}" e todos os seus itens?`)){state.projects=state.projects.filter(p=>p.id!==project().id);if(!state.projects.length){const p={id:uid(),name:'Novo projeto',items:[]};state.projects=[p]}state.activeProjectId=state.projects[0].id;save();render();toast('Projeto excluído')}}; $('#newItemBtn').onclick=()=>openItem(); $('#views').onclick=e=>{if(e.target.dataset.view){view=e.target.dataset.view;render()}}; $('#filters').onclick=e=>{if(e.target.dataset.filter){filter=e.target.dataset.filter;render()}}; $('#searchInput').oninput=e=>{query=e.target.value.toLowerCase();renderContent()}; document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close()); $('#blocked').onchange=()=>$('#blockReasonWrap').hidden=!$('#blocked').checked; $('#addChecklistBtn').onclick=()=>addCheck(); $('#itemForm').onsubmit=saveItem; $('#deleteItemBtn').onclick=deleteItem; $('#exportProjectBtn').onclick=()=>download(exportData([project()]),`${safe(project().name)}.json`); $('#exportAllBtn').onclick=()=>download(exportData(),'softtrack-todos-projetos.json'); $('#importInput').onchange=readImport; $('#importForm').onsubmit=applyImport; $('#clearBtn').onclick=()=>{if(confirm('Limpar todos os dados locais? Esta ação não pode ser desfeita.')){localStorage.removeItem(STORAGE_KEY);state=demo();save();render();toast('Dados locais reiniciados')}}; }
  function render(){const p=project();$('#projectSelect').innerHTML=state.projects.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${esc(x.name)}</option>`).join('');$('#projectName').textContent=p.name;const s=stats(p.items);$('#progressPercent').textContent=`${s.progress}%`;$('#progressBar').style.width=`${s.progress}%`;$('#missingCount').textContent=missing(p.items).length||'';document.querySelectorAll('#views button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('#filters button').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));renderContent()}
  function stats(items){const done=items.filter(i=>i.status==='Concluído').length,total=items.length, ongoing=items.filter(i=>i.status==='Em desenvolvimento').length;return {total,done,ongoing,bugs:items.filter(i=>i.type==='Bug'&&i.status!=='Concluído').length,tests:items.filter(i=>i.type==='Teste'&&i.status!=='Concluído').length,blocked:items.filter(i=>i.blocked||i.status==='Bloqueado').length,review:items.filter(i=>i.status==='Em revisão').length,checklist:items.reduce((n,i)=>n+(i.checklist||[]).filter(c=>!c.completed).length,0),progress:total?Math.round(done/total*100):0}}
  function pendingChecklist(i){return (i.checklist||[]).filter(c=>!c.completed).map((c,n)=>`${n+1}. ${c.title}\n\nInstruções:\n${c.description||'Sem instruções adicionais.'}`).join('\n\n')}
  function promptFor(items){const active=items.filter(i=>i.status!=='Concluído'),single=active.length===1;const blocks=[];const add=(title,value)=>{if(value?.trim())blocks.push(`${title}\n\n${value.trim()}`)};if(single){const i=active[0],checks=pendingChecklist(i),related=project().items.filter(x=>x.relatedId===i.id&&x.status!=='Concluído').map(x=>`- ${x.type}: ${x.title}`).join('\n');add('OBJETIVO',`Resolver as pendências abertas do item “${i.title}”.${i.description?`\n\n${i.description}`:''}`);add('PENDÊNCIAS',[checks,related].filter(Boolean).join('\n\n'));if(i.blocked)add('RESTRIÇÕES',`O trabalho está bloqueado: ${i.blockReason||'motivo ainda não informado.'}`);add('VALIDAÇÃO','Confirme que todas as pendências abertas foram resolvidas e que os cenários descritos nas instruções funcionam corretamente.');return blocks.join('\n\n')}const entries=active.map((i,n)=>{const checks=pendingChecklist(i);return `${n+1}. ${i.type.toUpperCase()} — ${i.title}${i.description?`\n\n${i.description}`:''}${checks?`\n\nChecklist pendente:\n${checks}`:''}${i.blocked?`\n\nBloqueio: ${i.blockReason||'motivo não informado'}`:''}`}).join('\n\n');add('OBJETIVO',`Resolver as pendências selecionadas do projeto “${project().name}”.`);add('PENDÊNCIAS',entries);add('VALIDAÇÃO','Ao finalizar, confirme que as instruções de cada checklist pendente foram atendidas e informe quais itens permanecem pendentes.');return blocks.join('\n\n')}
  function openPrompt(items){const pending=items.filter(i=>i.status!=='Concluído');if(!pending.length){toast('Não existem pendências para copiar');return}$('#promptPreview').value=promptFor(pending);$('#promptDialog').showModal()}
  function copyPrompt(){const text=$('#promptPreview').value;const done=()=>{toast('Prompt copiado!');$('#promptDialog').close()};if(navigator.clipboard?.writeText)navigator.clipboard.writeText(text).then(done).catch(()=>{ $('#promptPreview').select();document.execCommand('copy');done() });else{$('#promptPreview').select();document.execCommand('copy');done()}}
  function passes(i){return (!query||`${i.title} ${i.description} ${i.tags.join(' ')}`.toLowerCase().includes(query))&&(filter==='all'||(filter==='blocked'&&(i.blocked||i.status==='Bloqueado'))||(filter==='high'&&(i.priority==='Alta'||i.priority==='Crítica'))||i.type===filter)}
  function card(i){const related=project().items.filter(x=>x.relatedId===i.id), complete=related.filter(x=>x.status==='Concluído').length,checks=(i.checklist||[]).map(c=>`<div class="checklist-preview-item ${c.completed?'completed':''}"><span class="check-status">${c.completed?'☑':'☐'}</span><strong>${esc(c.title)}</strong></div>`).join('');return `<article class="card" draggable="true" data-id="${i.id}"><div class="card-top"><span class="type-pill type-${i.type.replace(' ','-')}">${esc(i.type)}</span>${i.blocked?'<span class="blocked">●</span>':''}</div><h3>${esc(i.title)}</h3>${checks?`<div class="checklist-preview">${checks}</div>`:''}<div class="card-bottom"><span class="priority-${i.priority}">● ${i.priority}</span><span>${related.length?`${complete}/${related.length} relacionados`:i.checklist.length?`${i.checklist.filter(c=>c.completed).length}/${i.checklist.length} checklist`:''}</span></div></article>`}
  function renderContent(){const p=project(), el=$('#content'),items=p.items.filter(passes);if(view==='board'){el.innerHTML=`<div class="board">${STATUSES.map(st=>{const its=items.filter(i=>i.status===st);return `<section class="column" data-status="${st}"><header class="column-head">${st}<span>${its.length}</span></header><div class="card-list">${its.map(card).join('')||'<p class="empty">Nenhum item</p>'}</div></section>`}).join('')}</div>`;bindCards();return}const s=stats(p.items);if(view==='missing'){const groups=missing(p.items),pending=p.items.filter(i=>i.status!=='Concluído');el.innerHTML=`<div class="stat-grid">${statCards(s)}</div><section class="missing-group"><h3>Pendências para IA</h3><button id="copyMissingPromptBtn">Copiar pendências selecionadas para IA</button><ul>${pending.map(i=>`<li><label><input type="checkbox" class="prompt-select" value="${i.id}" ${(i.priority==='Crítica'||i.priority==='Alta')?'checked':''}> ${esc(i.title)} — ${i.priority}</label></li>`).join('')}</ul></section><div class="missing-grid">${groups.map(g=>`<section class="missing-group"><h3>${g.icon} ${g.title} <span class="badge">${g.items.length}</span></h3><ul>${g.items.map(i=>`<li data-open="${i.id}">${esc(i.title)}</li>`).join('')}</ul></section>`).join('')||'<p class="empty">Nada pendente. Ótimo trabalho!</p>'}</div>`;return}const type=view==='bugs'?'Bug':'Teste';if(view===type.toLowerCase()+'s'||view==='bugs'||view==='tests'){const arr=p.items.filter(i=>i.type===type);el.innerHTML=`<div class="stat-grid">${statCards(s)}</div><div class="missing-grid"><section class="missing-group"><h3>${type}s</h3>${arr.length?`<ul>${arr.map(i=>`<li>${esc(i.title)} <small>— ${i.status}</small></li>`).join('')}</ul>`:'<p class="empty">Nenhum item.</p>'}</section></div>`;return}const pending=p.items.filter(i=>i.status!=='Concluído').sort((a,b)=>(b.blocked-a.blocked)||PRIORITIES.indexOf(a.priority)-PRIORITIES.indexOf(b.priority));el.innerHTML=`<div class="stat-grid">${statCards(s)}</div><section class="missing-group"><h3>Principais pendências</h3><ol class="summary-list">${pending.slice(0,8).map(i=>`<li>${i.blocked?'⛔ ':''}${esc(i.title)} <small>— ${i.status} · ${i.priority}</small></li>`).join('')||'<li>Projeto concluído.</li>'}</ol></section>`}
  function statCards(s){return [[s.total,'Total de itens'],[s.done,'Concluídos'],[s.ongoing,'Em andamento'],[s.bugs,'Bugs abertos'],[s.tests,'Testes pendentes'],[s.blocked,'Bloqueados'],[s.review,'Em revisão'],[s.checklist,'Checklist pendente']].map(x=>`<div class="stat"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}
  function missing(items){const f=(fn,title,icon='•')=>{const a=items.filter(fn);return a.length?{items:a,title,icon}:null};const funcs=items.filter(i=>i.type==='Funcionalidade');return [f(i=>i.type==='Funcionalidade'&&i.status!=='Concluído','Funcionalidades não concluídas','◈'),f(i=>i.type==='Bug'&&i.status!=='Concluído','Bugs abertos','🐞'),f(i=>i.type==='Bug'&&i.priority==='Crítica'&&i.status!=='Concluído','Bugs críticos','⚠'),f(i=>i.type==='Teste'&&i.status!=='Concluído','Testes pendentes','🧪'),f(i=>i.blocked||i.status==='Bloqueado','Trabalho bloqueado','⛔'),f(i=>i.status==='Em desenvolvimento','Em desenvolvimento','◐'),f(i=>i.status==='Em revisão','Aguardando revisão','⌕'),f(i=>i.type==='Documentação'&&i.status!=='Concluído','Documentação pendente','▤'),f(i=>(i.priority==='Alta'||i.priority==='Crítica')&&i.status!=='Concluído','Alta prioridade','▲'),f(i=>funcs.includes(i)&&!items.some(x=>x.relatedId===i.id&&x.type==='Teste'),'Funcionalidades sem testes','⚠')].filter(Boolean)}
  function bindCards(){
    document.querySelectorAll('.card').forEach(c=>{
      c.ondragstart=e=>{e.dataTransfer.setData('text/plain',c.dataset.id);c.classList.add('dragging')};
      c.ondragend=()=>c.classList.remove('dragging'); c.onclick=()=>openItem(c.dataset.id);
    });
    document.querySelectorAll('.column').forEach(c=>{
      c.ondragover=e=>{e.preventDefault();c.classList.add('drag-over')};
      c.ondragleave=()=>c.classList.remove('drag-over');
      c.ondrop=e=>{e.preventDefault();c.classList.remove('drag-over');const i=project().items.find(x=>x.id===e.dataTransfer.getData('text/plain'));if(i){i.status=c.dataset.status;i.blocked=i.status==='Bloqueado'||i.blocked;i.updatedAt=now();save();render();toast('Item movido')}};
    });
  }
  function options(arr,value){return arr.map(x=>`<option ${x===value?'selected':''}>${x}</option>`).join('')}
  function openItem(id){const i=project().items.find(x=>x.id===id);$('#itemForm').reset();$('#itemId').value=i?.id||'';$('#modalTitle').textContent=i?'Editar item':'Novo item';$('#type').innerHTML=options(TYPES,i?.type||'Tarefa');$('#priority').innerHTML=options(PRIORITIES,i?.priority||'Média');$('#status').innerHTML=options(STATUSES,i?.status||'Backlog');const rel=project().items.filter(x=>x.id!==i?.id);$('#relatedId').innerHTML='<option value="">Nenhum</option>'+rel.map(x=>`<option value="${x.id}" ${x.id===i?.relatedId?'selected':''}>${esc(x.title)}</option>`).join('');['title','description','tags','notes','blockReason'].forEach(k=>$('#'+k).value=k==='tags'?(i?.tags||[]).join(', '):(i?.[k]||''));$('#blocked').checked=!!i?.blocked;$('#blockReasonWrap').hidden=!i?.blocked;$('#checklistFields').innerHTML='';(i?.checklist||[]).forEach(addCheck);$('#deleteItemBtn').hidden=!i;const children=i?project().items.filter(x=>x.relatedId===i.id):[];$('#relatedSection').innerHTML=children.length?`<strong>Itens relacionados (${children.filter(x=>x.status==='Concluído').length} concluídos, ${children.filter(x=>x.blocked||x.status==='Bloqueado').length} bloqueados)</strong><ul>${children.map(x=>`<li>${esc(x.title)} — ${x.status}</li>`).join('')}</ul>`:'';$('#itemDialog').showModal()}
  function addCheck(c={title:'',description:'',completed:false}){const row=document.createElement('div');row.className='check-row';row.dataset.checkId=c.id||uid();row.innerHTML=`<input type="checkbox" aria-label="Concluir item do checklist" ${c.completed?'checked':''}><div class="check-fields"><input class="check-title" type="text" value="${esc(c.title||c.text)}" placeholder="O que precisa ser feito?"><label class="check-instructions-label">Instruções <button type="button" class="help" data-help="Descreva aqui o problema deste item, o que precisa ser feito e qualquer detalhe importante para executá-lo corretamente." aria-label="Ajuda sobre instruções">ⓘ</button><textarea class="check-desc" rows="3" placeholder="Descreva o problema, o que precisa ser feito e detalhes importantes.">${esc(c.description||'')}</textarea></label></div><button type="button" class="remove-check" aria-label="Remover item do checklist">×</button>`;row.querySelector('.remove-check').onclick=()=>row.remove();$('#checklistFields').append(row)}
  function saveItem(e){e.preventDefault();const p=project(), existing=p.items.find(i=>i.id===$('#itemId').value), type=$('#type').value;const data={title:$('#title').value.trim(),description:$('#description').value.trim(),type,priority:$('#priority').value,status:$('#status').value,tags:$('#tags').value.split(',').map(x=>x.trim()).filter(Boolean),relatedId:$('#relatedId').value,blocked:$('#blocked').checked,blockReason:$('#blockReason').value.trim(),notes:$('#notes').value.trim(),checklist:[...document.querySelectorAll('#checklistFields .check-row')].map(r=>({id:r.dataset.checkId||uid(),completed:r.querySelector('[type=checkbox]').checked,title:r.querySelector('.check-title').value.trim(),description:r.querySelector('.check-desc').value.trim()})).filter(c=>c.title),updatedAt:now()};if(existing)Object.assign(existing,data);else{const newI=item(data.title,type,data);p.items.push(newI);if(TEMPLATES[type]&&confirm(`Gerar ${TEMPLATES[type].length} tarefas relacionadas automaticamente?`)){TEMPLATES[type].forEach(([name,t])=>p.items.push(item(`${name}: ${data.title}`,t,{relatedId:newI.id,priority:data.priority})));}if(type==='Funcionalidade'&&!data.checklist.length)newI.checklist=DONE.map(text=>({id:uid(),title:text,description:'Critério necessário para considerar a funcionalidade pronta.',completed:false}));}save();$('#itemDialog').close();render();toast(existing?'Item atualizado':'Item criado')}
  function deleteItem(){const id=$('#itemId').value;if(confirm('Excluir este item? Os itens relacionados serão mantidos sem vínculo.')){project().items.forEach(i=>{if(i.relatedId===id)i.relatedId=''});project().items=project().items.filter(i=>i.id!==id);save();$('#itemDialog').close();render();toast('Item excluído')}}
  function download(data,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href);toast('Exportação preparada')};function safe(s){return s.replace(/[^a-z0-9]/gi,'-').toLowerCase()}
  function readImport(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const d=JSON.parse(reader.result);if(!valid(d))throw Error();importData=normalize(d);$('#importInfo').textContent=`Arquivo válido: ${d.projects.length} projeto(s). Escolha como combinar os dados.`;$('#importDialog').showModal()}catch{toast('JSON inválido ou incompatível')}};reader.readAsText(file);e.target.value=''}function applyImport(e){e.preventDefault();if(!importData)return;const mode=$('#importMode').value;if(mode==='replace')state=normalize(importData);else{const existing=new Set(state.projects.map(p=>p.id));const incoming=importData.projects.map(p=>existing.has(p.id)?{...p,id:uid(),name:`${p.name} (importado)`}:p);state.projects.push(...incoming);normalize(state)}if(importData.settings){settings=normalizeSettings(importData.settings);saveSettings();refreshBackupTimer()}state.activeProjectId=state.projects[0]?.id||'';save();$('#importDialog').close();render();toast('Dados importados com sucesso')}
  function destinationStatus(key){const destination=settings.destinations[key];if(!supportsBackup())return 'Indisponível neste navegador';if(!backupHandles[key])return destination.name?'Pasta precisa ser selecionada novamente.':'Nenhuma pasta selecionada';if(destination.status==='saved')return `✓ Salvo ${formatBackupDate(destination.lastAt)}`;if(destination.status==='failed')return '⚠ Não foi possível salvar';if(destination.status==='needs-permission')return '⚠ Precisa de autorização novamente';return 'Pronta para backup'}
  function destinationSettings(key,label,help){const destination=settings.destinations[key],configured=!!backupHandles[key],unavailable=!supportsBackup();return `<section class="backup-destination"><h4>${label} <button type="button" class="help" data-help="${help}" aria-label="Ajuda sobre ${label.toLowerCase()}">ⓘ</button></h4><p class="backup-folder">${destination.name?`✓ ${esc(destination.name)}`:'Nenhuma pasta selecionada'}</p><p class="backup-destination-status">${destinationStatus(key)}</p><div class="backup-destination-actions"><button type="button" class="ghost" data-backup-action="pick" data-backup-key="${key}" ${unavailable?'disabled':''}>${configured?'Alterar pasta':'Selecionar pasta'}</button>${configured?`<button type="button" class="ghost" data-backup-action="remove" data-backup-key="${key}">Remover pasta</button>`:''}${configured&&destination.status==='needs-permission'?`<button type="button" data-backup-action="authorize" data-backup-key="${key}">Autorizar novamente</button>`:''}</div></section>`}
  function settingsView(){const unavailable=!supportsBackup(),next=settings.nextBackup?`aproximadamente ${formatBackupDate(settings.nextBackup)}`:'Configure pelo menos uma pasta para usar o backup automático.';return `<section class="settings-view"><header><p class="eyebrow">PREFERÊNCIAS</p><h2>Configurações</h2><p class="settings-intro">Defina onde manter uma cópia externa dos dados deste projeto.</p></header><section class="settings-card"><div class="settings-card-head"><h3>Backup automático <button type="button" class="help" data-help="Cria periodicamente uma cópia JSON dos seus projetos em uma pasta escolhida por você." aria-label="Ajuda sobre backup automático">ⓘ</button></h3><label class="backup-toggle"><input id="autoBackup" type="checkbox" ${settings.autoBackup?'checked':''} ${unavailable?'disabled':''}> <span>${settings.autoBackup?'Ativado':'Desativado'}</span></label></div>${unavailable?'<p class="backup-warning">Seu navegador não permite selecionar uma pasta para backup automático. A exportação manual continua disponível.</p>':''}<label class="backup-interval">Intervalo <button type="button" class="help" data-help="Tempo entre uma execução automática de backup e outra." aria-label="Ajuda sobre intervalo">ⓘ</button><select id="backupInterval" ${settings.autoBackup&& !unavailable?'':'disabled'}><option value="10" ${settings.interval===10?'selected':''}>10 minutos</option><option value="30" ${settings.interval===30?'selected':''}>30 minutos</option><option value="60" ${settings.interval===60?'selected':''}>60 minutos</option></select></label><div class="backup-destinations">${destinationSettings('primary','Pasta principal','Primeiro local utilizado para manter uma cópia externa dos seus dados.')}${destinationSettings('secondary','Pasta secundária','Segundo local de backup. Ele também será tentado mesmo se houver falha na pasta principal.')}</div><div class="backup-actions"><button type="button" id="backupNowBtn" ${unavailable?'disabled':''}>Fazer backup agora</button></div><dl class="backup-status"><div><dt>Backup automático</dt><dd>${settings.autoBackup?'Ativado':'Desativado'}</dd></div><div><dt>Intervalo</dt><dd>${settings.interval} minutos</dd></div><div><dt>Última tentativa</dt><dd>${formatBackupDate(settings.lastAttempt)}</dd></div><div><dt>Próximo backup</dt><dd>${settings.autoBackup?next:'Ative o backup para agendar uma cópia.'}</dd></div></dl></section></section>`}
  function bindSettings(){const enabled=$('#autoBackup');if(!enabled)return;enabled.onchange=e=>{settings.autoBackup=e.target.checked;saveSettings();refreshBackupTimer();renderContent();if(settings.autoBackup&&!backupHandles.primary&&!backupHandles.secondary)toast('Configure pelo menos uma pasta para usar o backup automático.')};$('#backupInterval').onchange=e=>{settings.interval=Number(e.target.value);saveSettings();refreshBackupTimer();renderContent()};$('#backupNowBtn').onclick=()=>runBackup(true);document.querySelectorAll('[data-backup-action]').forEach(button=>button.onclick=()=>{const {backupAction:action,backupKey:key}=button.dataset;if(action==='pick')chooseBackupDirectory(key);if(action==='remove')removeBackupDirectory(key);if(action==='authorize')authorizeBackupDirectory(key)})}
  function enhanceBoardTooltips(){document.querySelectorAll('.column-head').forEach(head=>{const status=head.closest('.column').dataset.status,count=head.querySelector('span')?.textContent||'0';head.innerHTML=`<div class="column-title">${esc(status)} <button type="button" class="help" data-help="${STATUS_HELP[status]}" aria-label="Ajuda sobre ${esc(status)}">ⓘ</button></div><span>${count}</span>`})}
  const baseRenderContent=renderContent;renderContent=function(){if(view==='settings'){const content=$('#content');content.innerHTML=settingsView();bindSettings();return}const result=baseRenderContent();if(view==='board')enhanceBoardTooltips();return result};
  function downloadBackupFallback(automatic=false){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(exportData(),null,2)],{type:'application/json'}));a.download='softengine-backup.json';a.click();URL.revokeObjectURL(a.href);settings.lastAttempt=new Date().toISOString();settings.destinations.primary.status='downloaded';settings.destinations.primary.lastAt=settings.lastAttempt;saveSettings();renderBackupIndicator();if(!automatic)toast('Backup baixado. O Firefox usa a pasta padrão de downloads.')}
  const originalDestinationStatus=destinationStatus;destinationStatus=function(key){return supportsBackup()?originalDestinationStatus(key):'Use “Baixar backup agora” para salvar uma cópia.'};
  function browserDownloadSettingsView(){const next=settings.nextBackup?`aproximadamente ${formatBackupDate(settings.nextBackup)}`:'Ative o backup para agendar um download.';return `<section class="settings-view"><header><p class="eyebrow">PREFERÊNCIAS</p><h2>Configurações</h2><p class="settings-intro">Defina como manter uma cópia externa dos dados deste projeto.</p></header><section class="settings-card"><div class="settings-card-head"><h3>Backup por download <button type="button" class="help" data-help="Gera periodicamente uma cópia JSON para a pasta padrão de downloads do navegador." aria-label="Ajuda sobre backup por download">ⓘ</button></h3><label class="backup-toggle"><input id="autoBackup" type="checkbox" ${settings.autoBackup?'checked':''}> <span>${settings.autoBackup?'Ativado':'Desativado'}</span></label></div><p class="backup-warning">Este navegador não permite escolher ou sobrescrever uma pasta diretamente. Quando ativado, ele tentará baixar o JSON na pasta padrão de downloads. O navegador pode pedir confirmação, bloquear downloads repetidos ou criar arquivos duplicados.</p><label class="backup-interval">Intervalo <button type="button" class="help" data-help="Tempo entre uma tentativa automática de download e outra." aria-label="Ajuda sobre intervalo">ⓘ</button><select id="backupInterval"><option value="10" ${settings.interval===10?'selected':''}>10 minutos</option><option value="30" ${settings.interval===30?'selected':''}>30 minutos</option><option value="60" ${settings.interval===60?'selected':''}>60 minutos</option></select></label><section class="backup-destination"><h4>Destino</h4><p class="backup-folder">Downloads padrão do navegador</p><p class="backup-destination-status">${settings.destinations.primary.status==='downloaded'?`Último download: ${formatBackupDate(settings.destinations.primary.lastAt)}`:'Nenhum download realizado ainda'}</p></section><div class="backup-actions"><button type="button" id="backupNowBtn">Baixar backup agora</button></div><dl class="backup-status"><div><dt>Backup automático</dt><dd>${settings.autoBackup?'Ativado por download':'Desativado'}</dd></div><div><dt>Intervalo</dt><dd>${settings.interval} minutos</dd></div><div><dt>Última tentativa</dt><dd>${formatBackupDate(settings.lastAttempt)}</dd></div><div><dt>Próxima tentativa</dt><dd>${settings.autoBackup?next:'Ative o backup para agendar um download.'}</dd></div></dl></section></section>`}
  const originalSettingsView=settingsView;settingsView=function(){return supportsBackup()?originalSettingsView():browserDownloadSettingsView()};
  const originalBindSettings=bindSettings;bindSettings=function(){originalBindSettings();const button=$('#backupNowBtn');if(button&&!supportsBackup())button.onclick=downloadBackupFallback};
  document.addEventListener('click',e=>{if(!e.target.closest('.help'))$('#helpTooltip').hidden=true;if(e.target.closest('#backupIndicator')){view='settings';render()}});
  init();
})();
